PDA_Web/Areas/Admin/Controllers/BerthController.cs
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using PDAEstimator_Application.Interfaces;
using PDAEstimator_Domain.Entities;
using PDAEstimator_Infrastructure.Repositories;

namespace PDA_Web.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class BerthController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IToastNotification _toastNotification;
        public BerthController(IUnitOfWork unitOfWork, IToastNotification toastNotification)
        {
            this.unitOfWork = unitOfWork;
            _toastNotification = toastNotification;

        }

        public IActionResult Index()
        {
            var userid = HttpContext.Session.GetString("UserID");
            if (!string.IsNullOrEmpty(userid))
            {
                return View();
            }
            else
            {
                return RedirectToAction("index", "AdminLogin");
            }
        }
        public async Task<IActionResult> LoadAll()
        {
            var data = await unitOfWork.BerthDetails.GetAllAsync();
            //if (response.Succeeded)
            //{
            //    var viewModel = _mapper.Map<List<ProjectViewModel>>(response.Data);
            return PartialView("partial/_ViewAll", data);
            //}
        }

        public async Task<ActionResult> berthSave(BerthDetails berthDetails)
        {
            if (berthDetails.ID > 0)
            {
                await unitOfWork.BerthDetails.UpdateAsync(berthDetails);
                _toastNotification.AddSuccessToastMessage("Updated Successfully");
            }
            else
            {
                await unitOfWork.BerthDetails.AddAsync(berthDetails);
                _toastNotification.AddSuccessToastMessage("Inserted successfully");

            }
            return Json(new
            {
                proceed = true,
                msg = ""
            });
        }

        public async Task<ActionResult> editBerth(BerthDetails berthDetails)
        {
            var data = await unitOfWork.BerthDetails.GetByIdAsync(berthDetails.ID);
            return Json(new
            {
                berths = data,
                proceed = true,
                msg = ""
            });
        }

        public async Task<ActionResult> deleteBerth(BerthDetails berthDetails)
        {
            var data = await unitOfWork.BerthDetails.DeleteAsync(berthDetails.ID);
            _toastNotification.AddSuccessToastMessage("Deleted Successfully");
            return Json(new
            {
                proceed = true,
                msg = ""
            });
        }
    }
}

PDA_Web/Controllers/PDAController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using PDA_Web.Models;
using PDAEstimator_Application.Interfaces;
using PDAEstimator_Domain.Entities;
using PDAEstimator_Infrastructure.Repositories;
using PDAEstimator_Infrastructure_Shared;
using PDAEstimator_Infrastructure_Shared.Services;
using Rotativa.AspNetCore;
using SelectPdf;
using System.Data;
using System.Globalization;

namespace PDA_Web.Controllers
{
    public class PDAController : Controller
    {
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IUnitOfWork unitOfWork;
        private readonly IToastNotification _toastNotification;
        private readonly IEmailSender _emailSender;

        public PDAController(IUnitOfWork unitOfWork, IToastNotification toastNotification, IWebHostEnvironment hostEnvironment, IEmailSender emailSender)
        {
            this.unitOfWork = unitOfWork;
            _toastNotification = toastNotification;
            _hostEnvironment = hostEnvironment;
            _emailSender = emailSender;

        }
        public IActionResult OpenBerthDetailsPopUp(PDAEstimator PDAEstimitor)
        {
            var BearthDetailData = unitOfWork.BerthDetails.GetAllAsync().Result.Where(x => x.TerminalID == PDAEstimitor.TerminalID);
            if (BearthDetailData != null && BearthDetailData.Count() > 0)
                BearthDetailData = BearthDetailData.Where(x => x.BerthStatus == true).ToList();
            var Terminals = PartialView("partial/_Berths", BearthDetailData);
            return PartialView("partial/_Berths", BearthDetailData);
        }

        public async Task<IActionResult> CurrencyOnchange(int Currency)
        {
            var roedata = await unitOfWork.Rates.GetAlllistbyLoadAllforDefaultRoEName();
            var roeRate = roedata.Where(x => x.ID == Currency).FirstOrDefault();


            return Json(new
            {
                roeRate = roeRate == null ? 0 : roeRate.ROERate,
                proceed = true,
                msg = ""
            });
        }

        public async Task<IActionResult> PDAEstimatorDonwload(int id)
        {
            PDAEstimatorOutPutView pDAEstimatorOutPut = new PDAEstimatorOutPutView();
            pDAEstimatorOutPut = await GetPDA(id);
            //string PDAfilename = "PDA_" + pDAEstimatorOutPut.PortName + "_" + pDAEstimatorOutPut.PDAEstimatorID + ".pdf";
            //string path = $"{_hostEnvironment.WebRootPath}\\PDAFile\\";
            //var rootpath = Path.Combine(path, PDAfilename);
            //rootpath = Path.GetFullPath(rootpath);
            return new ViewAsPdf("PDAEstimator", pDAEstimatorOutPut)
            {
                //FileName = "MyPdf.pdf";
                FileName = "PDA_" + pDAEstimatorOutPut.PortName + "_" + pDAEstimatorOutPut.ActivityType + "_ " + pDAEstimatorOutPut.CargoName + "_" + pDAEstimatorOutPut.PDAEstimatorID + ".pdf",
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Portrait,
                PageSize = Rotativa.AspNetCore.Options.Size.A3
            };
        }

        public async Task<IActionResult> PDAEstimatorDownloadandSave(int id)
        {
            PDAEstimatorOutPutView pDAEstimatorOutPut = new PDAEstimatorOutPutView();
            pDAEstimatorOutPut = await GetPDA(id);
            string PDAfilename = "PDA_" + pDAEstimatorOutPut.PortName + "_" + pDAEstimatorOutPut.ActivityType + "_ " + pDAEstimatorOutPut.CargoName + "_" + pDAEstimatorOutPut.PDAEstimatorID + ".pdf";
            string path = $"{_hostEnvironment.WebRootPath}\\PDAFile\\";
            var rootpath = Path.Combine(path, PDAfilename);
            rootpath = Path.GetFullPath(rootpath);
            return new ViewAsPdf("PDAEstimator", pDAEstimatorOutPut)
            {
                //FileName = "MyPdf.pdf";
                FileName = "PDA_" + pDAEstimatorOutPut.PortName + "_" + pDAEstimatorOutPut.ActivityType + "_ " + pDAEstimatorOutPut.CargoName + "_" + pDAEstimatorOutPut.PDAEstimatorID + ".pdf",
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Portrait,
                PageSize = Rotativa.AspNetCore.Options.Size.A3,
                SaveOnServerPath = rootpath
            };
        }

        public async Task<IActionResult> PDAEstimatorEmail(int id)
        {
            PDAEstimatorOutPutView pDAEstimatorOutPut = new PDAEstimatorOutPutView();
            pDAEstimatorOutPut = await GetPDA(id);
            string PDAfilename = "PDA_" + pDAEstimatorOutPut.PortName + "_"+ pDAEstimatorOutPut.ActivityType + "_ " + pDAEstimatorOutPut.CargoName + "_" + pDAEstimatorOutPut.PDAEstimatorID + ".pdf";
            string path = $"{_hostEnvironment.WebRootPath}\\PDAFile\\";
            var rootpath = Path.Combine(path, PDAfilename);
            rootpath = Path.GetFullPath(rootpath);

            var custid = HttpContext.Session.GetString("ID");

            if (!string.IsNullOrEmpty(custid))
            {
                var custuser = unitOfWork.CustomerUserMaster.GetByIdAsync(Convert.ToInt32(custid)).Result;

                if (custuser != null)
                {
                    string customerfullname = string.Concat(custuser.FirstName, ' ', custuser.LastName);

                    string Content = "<html><head><title> PDA .</title></head><body><p> Dear "+ customerfullname + ", <br><br>  Please find attached PDA "+ id + " for Port "+ pDAEstimatorOutPut.PortName + " For further details/query on the attached PDA, you may connect/email us on bulkopsindia@samsarashipping.com <br> Please email your feedback/suggestions to EPDA.Support@samsaragroup.com  <br><br> <b>Regards <br> EPDA Portal Team</b> </p></body></html>";
                    string Subject = "EPDA Portal: PDA "+ id + " for Port "+ pDAEstimatorOutPut.PortName;
                    List<string> ccrecipients = new List<string>();

                    List<string> recipients = new List<string>
                    {
                        custuser.Email
                    };
                    string FromCompany = "";
                    string ToEmail = "";

                   var customer = await unitOfWork.Customer.GetByIdAsync(custuser.CustomerId);
                    var companydata = await unitOfWork.Company.GetAlllistAsync();
                    int Samsaracompanyid = 0;
                    if (companydata != null && companydata.Count > 0)
                    {
                        var samsaracompanydata = companydata.Where(x => x.CompanyName.ToLower() == "samsara shipping private limited");
                        if (samsaracompanydata.Count() > 0)
                        {
                            Samsaracompanyid = samsaracompanydata.FirstOrDefault().CompanyId;
                        }
                    }

                    int companyid = customer.PrimaryCompanyId != null ? (int)customer.PrimaryCompanyId : Samsaracompanyid;

                    var emailconfig = await unitOfWork.EmailNotificationConfigurations.GetByCompanyandProcessNameAsync(companyid, "PDA Generate");
                    if (emailconfig != null)
                    {
                        ToEmail = emailconfig.ToEmail;
                        FromCompany = emailconfig.FromEmail;
                        if (emailconfig.ToEmail != null)
                        {
                            ccrecipients = ToEmail.Split(',').ToList();
                        }
                    }

                    var Msg = new Message(recipients, ccrecipients, Subject, Content, FromCompany);
                    /*            _toastNotification.AddSuccessToastMessage("Email hase been sent to given Email Address");*/
                    _emailSender.SendEmail(Msg, rootpath);
                }
            }
            return Json(new
            {
                proceed = true,
                msg = ""
            });
        }

        public async Task<PDAEstimatorOutPutView> GetPDA(int id)
        {
            //PDAEstimatorOutPutView pDAEstimatorOutPut = new PDAEstimatorOutPutView();
            //pDAEstimatorOutPut = await PDAModelPrePared(pDAEstimatorOutPut, id);

            PDAEstimatorOutPutView pDAEstimatorOutPutView = new PDAEstimatorOutPutView();

            var pDAEstimatorOutPutdata = await unitOfWork.PDAEstimitorOUTPUT.GetByIdAsync(Convert.ToInt64(id));
            if (pDAEstimatorOutPutdata != null)
            {
                var PDAData = unitOfWork.PDAEstimitor.GetAlllistAsync().Result.Where(x => x.PDAEstimatorID == id).FirstOrDefault();
                var TaxData = unitOfWork.Taxs.GetAllAsync().Result;

                pDAEstimatorOutPutView = new PDAEstimatorOutPutView()
                {
                    PDAEstimatorID = PDAData.PDAEstimatorID,
                    CustomerID = PDAData.CustomerID,
                    FirstName = PDAData.CustomerCompanyName,
                    VesselName = PDAData.VesselName,
                    PortName = PDAData.PortName,
                    PortID = PDAData.PortID,
                    ActivityTypeId = PDAData.ActivityTypeId,
                    BerthStayDay = PDAData.BerthStayDay,
                    TerminalName = PDAData.TerminalName,
                    ETA = PDAData.ETA,
                    ActivityType = PDAData.ActivityType,
                    TerminalID = PDAData.TerminalID,
                    CallTypeName = PDAData.CallTypeName,
                    CallTypeID = PDAData.CallTypeID,
                    CurrencyName = PDAData.CurrencyName,
                    CargoID = PDAData.CargoID,
                    CargoQty = PDAData.CargoQty,
                    CargoQtyCBM = PDAData.CargoQtyCBM,
                    CargoUnitofMasurement = PDAData.CargoUnitofMasurement,
                    LoadDischargeRate = PDAData.LoadDischargeRate,
                    CargoName = PDAData.CargoName,
                    CurrencyID = PDAData.CurrencyID,
                    ROE = PDAData.ROE,
                    DWT = PDAData.DWT,

PDA_Web/Views/PDA/partial/BerthList.cshtml
<label for="PortName">Berth<span class="text-danger">*</span></label>
@Html.DropDownList("BerthName", new SelectList(ViewBag.Berth, "ID", "BerthName"), "Please Select", new { @class = "form-control", @onchange = "BerthChangefunc(this.value)" })

PDA_Web/Views/PDA/partial/CompanyName.cshtml
<label for="Company"> Company</label>
@Html.DropDownList("Company", new SelectList(ViewBag.Customers, "CompanyId", "CompanyName"), "Please select", new { @class = "form-control" })

PDA_Web/Views/PDA/partial/TerminalList.cshtml
<label for="PortName">Terminal<span class="text-danger">*</span></label>
@Html.DropDownList("TerminalName", new SelectList(ViewBag.Terminal, "ID", "TerminalName"), "Please Select", new { @class = "form-control" , @onchange = "callChangefunc(this.value)" })

PDA_Web/Views/PDA/partial/_CargoList.cshtml
<label for="Cargo">Cargo<span class="text-danger">*</span></label>
@Html.DropDownList("CargoName", new SelectList(ViewBag.Cargo, "ID", "CargoName"), "Please select", new { @class = "form-control", @onchange = "CargoNameOnChangefunc()" })

PDA_Web/Views/PDA/partial/_ViewAll.cshtml
@model IEnumerable<PDAEstimator_Domain.Entities.PDAEstimatorList>
@using PDAEstimator_Domain.Entities;
<style>
    table td {
        width: 14px;
        word-wrap: break-word;
    }
</style>
<table class="table table-bordered table-striped" id="PDAEstimator">
    <thead>

        <tr>
            <th>
                PDA ID
            </th>
           @*  <th>
                Customer Name
            </th>
            <th style="min-width:150px">
                @Html.DisplayNameFor(model => model.CustomerCompanyName)
            </th> *@
            <th>
                @Html.DisplayNameFor(model => model.VesselName)
            </th>
            <th>
                Port Name
            </th>
            <th>
                Port Information(Dry Bulk)
            </th>
            <th>
                Port Information(Tanker)
            </th>
            <th style="min-width:120px">
                Port Activity Type
            </th>
            <th style="min-width:180px">
                Terminal Name
            </th>
            <th style="min-width:180px">
                BerthName
            </th>
            <th style="min-width:110px">
                Call Type
            </th>

            <th style="min-width:150px">
                Cargo Name
            </th>
            <th>
                Cargo Qty
            </th>
            <th style="min-width:150px">
                Cargo Unit of Masurement
            </th>
            <th>
                Load/Discharge Rate
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrencyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ROE)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DWT )
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArrivalDraft)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GRT)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NRT)
            </th>
            <th style="min-width:100px">
                Berth Stay Hours Foreign
            </th>
            <th style="min-width:100px">
                Berth Stay Day Foreign
            </th>
            <th style="min-width:100px">
                Berth Stay Shift Foreign
            </th>
            <th style="min-width:120px">
                Berth Stay Hours Coastal)
            </th>
            <th style="min-width:100px">
                Berth Stay Day Coastal
            </th>
            <th style="min-width:100px">
                Berth Stay Shift Coastal
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AnchorageStay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LOA)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Beam)
            </th>
            <th style="min-width:70px">
                @Html.DisplayNameFor(model => model.ETA)
            </th>
            <th>Vessel Ballast</th>
            <th>IsReducedGRT</th>
            <th>CreatedBy</th>
            <th>CreationDate</th>
            @*             <th>ModifyUserID</th>
            <th>ModifyDate</th> *@

            <th style="min-width:200px"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PDAEstimatorID)
                </td>
               @*  <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerCompanyName)
                </td> *@
                <td>
                    @Html.DisplayFor(modelItem => item.VesselName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PortName)
                </td>
                <td width="20">
                    @if (item.PortFile != null)
                        @Html.ActionLink(item.PortFile, "DownloadFile", new { fileName = item.PortFile })
                    @*@Html.DisplayFor(modelItem => item.PortFile)*@
                </td>
                <td width="20">
                    @if (item.PortFileTanker != null)
                        @Html.ActionLink(item.PortFileTanker, "DownloadFile", new { fileName = item.PortFileTanker })
                    @*@Html.DisplayFor(modelItem => item.PortFile)*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ActivityType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TerminalName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BerthName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CallTypeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CargoName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CargoQty)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CargoUnitofMasurement)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LoadDischargeRate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrencyName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ROE)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DWT)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.ArrivalDraft)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GRT)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NRT)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BerthStay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BerthStayDay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BerthStayShift)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BerthStayHoursCoastal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BerthStayDayCoastal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BerthStayShiftCoastal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AnchorageStay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LOA)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Beam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ETA)
                </td>

                @*                 <td>
            @Html.DisplayFor(modelItem => item.VesselBallast)
            </td> *@
                <td>

                    @if (item.VesselBallast == 1)
                    {
                        <span class="badge badge-danger">No</span>
                    }
                    else
                    {
                        <span class="badge badge-success">Yes</span>
                    }

                </td>
                <td>

                    @if (item.IsReducedGRT == 1)
                    {
                        <span class="badge badge-danger">No</span>
                    }
                    else
                    {
                        <span class="badge badge-success">Yes</span>
                    }

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreationDate)
                </td>
                @*                 <td>
            @Html.DisplayFor(modelItem => item.ModifyUser)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.ModifyDate)
            </td> *@

                @{

                    @if (ViewBag.UserPermissionModel != null)
                    {
                        List<UserPermissionRights> userPermissionRights = new List<UserPermissionRights>();
                        List<UserRoleName> userRoleName = new List<UserRoleName>();
                        userPermissionRights = ViewBag.UserPermissionModel;


                        userRoleName = ViewBag.UserRoleName;

                        <td min-width="230px">
                            @if (userRoleName.Where(x => x.RoleName == "Admin").Count() > 0 || (userPermissionRights.Where(x => x.MenuName == "PDA Estimator" && x.UserRolePermission == "ViewPDA").Count() > 0))
                            {
                                <a class="btn btn-info btn-sm" onclick="EditPDAEstimator(@item.PDAEstimatorID, 'Copy')">
                                    <i class="fas fa-pencil-alt"></i> Copy
                                </a>
                                <a class="btn btn-warning btn-sm" href="@Url.Action("PDAEstimatorDonwload", "PDA", new { id = @item.PDAEstimatorID})" target="_blank">
                                    <i class="fas fa-download"></i> Download
                                </a>
                                <a class="btn btn-success btn-sm" href="@Url.Action("PDAEstimator", "PDA", new { id = @item.PDAEstimatorID})" target="_blank">
                                    <i class="fas fa-eye"></i> View
                                </a>
                            }

                            @if (userRoleName.Where(x => x.RoleName == "Admin").Count() > 0 || (userPermissionRights.Where(x => x.MenuName == "PDA Estimator" && x.UserRolePermission == "Delete").Count() > 0))
                            {
                                <a class="btn btn-danger btn-sm" onclick="deletePDAEstimator(@item.PDAEstimatorID)">
                                    <i class="fas fa-trash"></i> Delete
                                </a>
                            }

                        </td>
                    }

                }
            </tr>
        }


    </tbody>
</table>
<!-- jQuery -->
<script src="~/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/plugins/datatables/jquery.datatables.js"></script>
<script src="~/plugins/datatables/jquery.datatables.min.js"></script>
<script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="~/plugins/jszip/jszip.min.js"></script>
<script src="~/plugins/pdfmake/pdfmake.min.js"></script>
<script src="~/plugins/pdfmake/vfs_fonts.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<script>




    $(document).ready(function () {
        $("#PDAEstimator").DataTable({
            order: [[0, 'desc']],
            scrollX: true,
            scrollCollapse: true,
            scrollY: '400px',
            fixedHeader: {
                header: true,
            },
            "responsive": false, "lengthChange": false, "autoWidth": false,
            "buttons": [{
                extend: 'excel',
                text: 'Export Results',
                className: 'btn btn-default',
                exportOptions: {
                    columns: 'th:not(:last-child)'
                }
            }]
        }).buttons().container().appendTo('#PDAEstimator_wrapper .col-md-6:eq(0)');

    });</script>